/** @format */

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-black text-white p-3">
          <div className="flex gap-2">
            <Link href="/dashboard">dashboard</Link>
            <Link href="/about-us">about us</Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
